name: 'Unit Tests'
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
jobs:
  Sqlite:
    runs-on: ubuntu-latest
    steps:
    # - name: Install system dependencies
    #   run: |
    #     sudo apt-get update -y
    #     sudo apt-get install -y \
    #       php-cli \
    #       php-mbstring \
    #       php-sqlite3 \
    #       php-opcache \
    #       php-json \
    #       php-ldap \
    #       php-gd \
    #       php-zip \
    #       php-curl \
    #       php-xml \
    #       php-mysql \
    #       php-pgsql \
    #       composer \
    #       npm \
    #       mariadb-client \
    #       postgresql-client \
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, sqlite3, json, openssl, curl, zip, gd
        tools: composer
    - name: Checkout Kanboard repo
      uses: actions/checkout@v2
      with:
        repository: kanboard/kanboard
    - name: Checkout Plugin repo
      uses: actions/checkout@v2
      with:
        path: plugins/Wiki
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: List files
      run: |
        ls -la
    - name: Unit tests with Sqlite
      run: ./vendor/bin/phpunit -c tests/units.sqlite.xml plugins/Wiki/Test/

  Postgres:
    runs-on: ubuntu-latest
    # container: kanboard/tests:latest
    needs: Sqlite
    services:
      postgres:
        image: postgres:9.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql, json, openssl, curl, zip, gd
        tools: composer
    - name: Checkout Kanboard repo
      uses: actions/checkout@v2
      with:
        repository: kanboard/kanboard
    - name: Checkout Plugin repo
      uses: actions/checkout@v2
      with:
        path: plugins/Wiki
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Unit tests with Postgres
      run: ./vendor/bin/phpunit -c tests/units.postgres.xml plugins/Wiki/Test/
      env:
        DB_HOSTNAME: postgres
        DB_PORT: ${{ job.services.postgres.ports[5432] }}
 
  MariaDB:
    runs-on: ubuntu-latest
    # container: kanboard/tests:latest
    needs: Sqlite
    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: secret
        ports:
        - 3306:3306
        options: >-
          --health-cmd "healthcheck.sh --connect --innodb_initialized"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, json, openssl, curl, zip, gd
        tools: composer
    - name: Checkout Kanboard repo
      uses: actions/checkout@v2
      with:
        repository: kanboard/kanboard
    - name: Checkout Plugin repo
      uses: actions/checkout@v2
      with:
        path: plugins/Wiki
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Unit tests with MariaDB
      run: ./vendor/bin/phpunit -c tests/units.mysql.xml plugins/Wiki/Test/
      env:
        DB_HOSTNAME: mariadb
        DB_PASSWORD: secret
        DB_PORT: ${{ job.services.mariadb.ports[3306] }}